version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
- package-ecosystem: "github-actions"
  # Workflow files stored in the default location of `.github/workflows`
  directory: "/"
  schedule:
    interval: "daily"
