stages:
  - test
  - deploy

showroom:
    stage: test
    before_script:
        - /bin/bash $CACHE_DIR/bundlerScript.bash
        - brew install swiftgen
    script:
        - bundle exec fastlane testProduction
    tags:
        - xcode-8.0
    except:
        - tags

showroom_worldwide:
    stage: test
    before_script:
        - /bin/bash $CACHE_DIR/bundlerScript.bash
        - brew install swiftgen
    script:
        - bundle exec fastlane testProductionWorldwide
    tags:
        - xcode-8.0
    except:
        - tags

showroom_kids:
    stage: test
    before_script:
        - /bin/bash $CACHE_DIR/bundlerScript.bash
        - brew install swiftgen
    script:
        - bundle exec fastlane testProductionKids
    tags:
        - xcode-8.0
    except:
        - tags

showroom_deploy_staging:
    stage: deploy
    before_script:
        - /bin/bash $CACHE_DIR/bundlerScript.bash
        - brew install swiftgen
    script:
        - bundle exec fastlane deployStaging
    tags:
        - xcode-8.0
    only:
        - tags

showroom_deploy_production:
    stage: deploy
    before_script:
        - /bin/bash $CACHE_DIR/bundlerScript.bash
        - brew install swiftgen
    script:
        - bundle exec fastlane deployProduction
    tags:
        - xcode-8.0    
    only:
        - tags    

showroom_worldwide_deploy_staging:
    stage: deploy
    before_script:
        - /bin/bash $CACHE_DIR/bundlerScript.bash
        - brew install swiftgen
    script:
        - bundle exec fastlane deployStagingWorldwide
    tags:
        - xcode-8.0
    only:
        - tags

showroom_worldwide_deploy_production:
    stage: deploy
    before_script:
        - /bin/bash $CACHE_DIR/bundlerScript.bash
        - brew install swiftgen
    script:
        - bundle exec fastlane deployProductionWorldwide
    tags:
        - xcode-8.0    
    only:
        - tags

showroom_kids_deploy_staging:
    stage: deploy
    before_script:
        - /bin/bash $CACHE_DIR/bundlerScript.bash
        - brew install swiftgen
    script:
        - bundle exec fastlane deployStagingKids
    tags:
        - xcode-8.0
    only:
        - tags

showroom_kids_deploy_production:
    stage: deploy
    before_script:
        - /bin/bash $CACHE_DIR/bundlerScript.bash
        - brew install swiftgen
    script:
        - bundle exec fastlane deployProductionKids
    tags:
        - xcode-8.0    
    only:
        - tags