language: objective-c
env: WORKDIR=Showroom/
xcode_project: Showroom.xcodeproj
xcode_scheme: 
 - Showroom
 - ShowroomStaging
 - ShowroomAppStore
xcode_sdk:
 - iphoneos
xcode_version:
 - '7.3'

script:
- brew install carthage
- brew install swiftgen
- polidea-ci/script

install:
- git clone $POLIDEA_CI_REPOSITORY polidea-ci
- polidea-ci/install
after_success:
- polidea-ci/upload_artifacts