language: objective-c
osx_image: xcode11.3
podfile: BuyPolish/Podfile

before_script: cd BuyPolish

jobs:
  include:
    - stage: test
      name: "Unit tests"
      script: fastlane unit_tests
    - name:  "UI tests"
      script: fastlane ui_tests

after_script: cd ..

cache:
  bundler: true
  cocoapods: true

after_failure:
  - npm install imgur-upload-cli
  - ./node_modules/.bin/imgur-upload BuyPolish/PolaUITests/SnapshotFailedTests/*.png
  - ./node_modules/.bin/imgur-upload BuyPolish/PolaUITests/FailureDiffs/**/*.png

notifications:
  email: false
