language: objective-c

xcode_workspace: Pola.xcworkspace
xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 8
osx_image: xcode11.3

before_install: 
  - cd BuyPolish

jobs:
  include:
    - stage: test
      name: "Unit tests"
      xcode_scheme: Pola
    - name:  "UI tests"
      xcode_scheme: PolaUITests

cache:
  directories:
  - BuyPolish/Pods

after_failure:
  - npm install imgur-upload-cli
  - ./node_modules/.bin/imgur-upload PolaUITests/SnapshotFailedTests/*.png
  - ./node_modules/.bin/imgur-upload PolaUITests/FailureDiffs/**/*.png

notifications:
  email: false
