language: objective-c
osx_image: xcode11.3
podfile: BuyPolish/Podfile

before_script: cd BuyPolish
script: fastlane tests
after_script: cd ..

cache:
  bundler: true
  cocoapods: true

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - npm install imgur-upload-cli
  - ./node_modules/.bin/imgur-upload BuyPolish/PolaUITests/SnapshotFailedTests/*.png
  - ./node_modules/.bin/imgur-upload BuyPolish/PolaUITests/FailureDiffs/**/*.png

notifications:
  email: false
