language: objective-c

xcode_workspace: Pola.xcworkspace
xcode_scheme: Pola
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone 8
osx_image: xcode10.2

before_install: cd BuyPolish

notifications:
  email: false
