language: objective-c

xcode_workspace: BuyPolish/Pola.xcworkspace
xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 8
osx_image: xcode11.3
podfile: BuyPolish/Podfile

jobs:
  include:
    - stage: test
      name: "Unit tests"
      xcode_scheme: Pola
    - name:  "UI tests"
      xcode_scheme: PolaUITests

cache:
  bundler: true
  cocoapods: true

after_failure:
  - npm install imgur-upload-cli
  - ./node_modules/.bin/imgur-upload BuyPolish/PolaUITests/SnapshotFailedTests/*.png
  - ./node_modules/.bin/imgur-upload BuyPolish/PolaUITests/FailureDiffs/**/*.png

notifications:
  email: false
