language: objective-c

xcode_workspace: Pola.xcworkspace
xcode_destination: platform=iOS Simulator,OS=13.1,name=iPhone 8
osx_image: xcode11.1

before_install: 
  - cd BuyPolish

jobs:
  include:
    - stage: test
      name: "Unit tests"
      xcode_scheme: Pola
    - name:  "UI tests"
      xcode_scheme: PolaUITests

cache:
  directories:
  - BuyPolish/Pods

notifications:
  email: false
