excluded: # paths to ignore during linting. overridden by `included`.
  - Pods
  - Pola/R.generated.swift
  - PolaTests/AutoMockable.generated.swift

opt_in_rules:
  - empty_count
  - file_header
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - first_where
  - sorted_imports
  - prohibited_super_call
  - fatal_error_message

disabled_rules:
  - identifier_name
  - type_name
  - line_length
  - function_body_length
  - todo
  - trailing_comma


comma: error
colon:
  severity: error

file_header:
  forbidden_pattern: //
