source 'https://cdn.cocoapods.org/'

platform :ios, '8.0'
inhibit_all_warnings!

target :Pola do
    use_frameworks!
    pod 'Firebase/Crashlytics', '~> 6.33.0'
    pod 'Firebase/Analytics', '~> 6.33.0'
    pod 'UITextView+Placeholder'
    pod 'KVNProgress'
    pod 'R.swift'
    pod 'Alamofire'
    pod 'Swinject'
    pod 'PromiseKit/Alamofire'
    pod 'Observable'
    
    target :PolaTests do
      pod 'iOSSnapshotTestCase'
    end
    
    target :PolaUITests do
      pod 'iOSSnapshotTestCase'
      pod 'Swifter', '~> 1.4.7'
    end

end

pod 'SwiftFormat/CLI'
pod 'SwiftLint'
