source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'
inhibit_all_warnings!
use_frameworks!

target :Pola do

  pod 'Firebase/Messaging'
  pod 'Firebase/Performance'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'

  pod 'UITextView+Placeholder'
  pod 'KVNProgress'
  pod 'R.swift'
  pod 'Alamofire'
  pod 'Swinject'
  pod 'PromiseKit/Alamofire'
  pod 'Observable'

  target :PolaTests do
    pod 'SnapshotTesting'
    pod 'DataDrivenTesting'
  end
    
  target :PolaUITests do
    pod 'Swifter'
    pod 'SnapshotTesting'
  end

end

target :NotificationServiceExtension do
  pod 'Firebase/Messaging'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end

pod 'SwiftFormat/CLI'
pod 'SwiftLint'
pod 'Sourcery'
