source 'https://cdn.cocoapods.org/'

platform :ios, '11.0'
inhibit_all_warnings!

target :Pola do
    use_frameworks!
    pod 'Firebase/Analytics'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Performance'
    pod 'UITextView+Placeholder'
    pod 'KVNProgress'
    pod 'R.swift'
    pod 'Alamofire'
    pod 'Swinject'
    pod 'PromiseKit/Alamofire'
    pod 'Observable'
    
    target :PolaTests do
      pod 'SnapshotTesting'
    end
    
    target :PolaUITests do
      pod 'Swifter'
      pod 'SnapshotTesting'
    end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end

pod 'SwiftFormat/CLI'
pod 'SwiftLint'
