name: Deploy to TestFlight

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Number version to deploy'
        required: true

jobs:
  bump_version:
    name: Deploy 
    runs-on: macos-10.15
    defaults:
      run:
        working-directory: BuyPolish

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
          token: ${{ secrets.WORKFLOW_ACCESS_TOKEN_GITHUB }}
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Cache bundler gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Cache pods
        uses: actions/cache@v3
        with:
          path: BuyPolish/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Bundler
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Pod install
        run: bundle exec pod install
      - name: Update Firebase config
        run: |
          rm Pola/GoogleService-Info.plist
          echo $DEV_ENV_FILE >> Pola/GoogleService-Info.plist
        shell: bash
        env:
          DEV_ENV_FILE : ${{secrets.GOOGLE_SERVICE_INFO_CONTENT}}
      - name: Deploy to TestFlight
        run: bundle exec fastlane deploy version:${{ github.event.inputs.version }}
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
