name: Tests

on: [push, pull_request]

jobs:
  build:
    name: Lint, unit & ui tests
    runs-on: macos-10.14
    defaults:
      run:
        working-directory: BuyPolish

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bundler
        run: bundle install
      - name: Pod install
        run: bundle exec pod install
      - name: Run tests
        run: bundle exec fastlane tests
      - name: Codecov
        uses: codecov/codecov-action@v1.0.13
      - name: "Upload PolaUITests-SnapshotFailedTests"
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: PolaUITests-SnapshotFailedTests
          path: BuyPolish/PolaUITests/SnapshotFailedTests
      - name: "Upload PolaUITests-FailureDiffs"
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: PolaUITests-FailureDiffs
          path: BuyPolish/PolaUITests/FailureDiffs
      - name: "Upload PolaTests-FailureDiffs"
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: PolaTests-FailureDiffs
          path: BuyPolish/PolaTests/FailureDiffs


