name: Tests

on: [push, pull_request]

jobs:
  build:
    name: Lint, unit & ui tests
    runs-on: macos-10.14
    defaults:
      run:
        working-directory: BuyPolish

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bundler
        run: bundle install
      - name: Pod install
        run: bundle exec pod install
      - name: Run tests
        run: bundle exec fastlane tests
      - name: Codecov
        uses: codecov/codecov-action@v1.0.13
