name: Tests

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    name: Lint, unit & ui tests
    runs-on: macos-10.14
    defaults:
      run:
        working-directory: BuyPolish

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache bundler gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Cache pods
        uses: actions/cache@v2
        with:
          path: BuyPolish/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Bundler
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Pod install
        run: bundle exec pod install
      - name: Run tests
        run: bundle exec fastlane tests
      - name: Codecov
        uses: codecov/codecov-action@v1.0.13
      - name: "Upload PolaUITests-SnapshotFailedTests"
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: PolaUITests-SnapshotFailedTests
          path: BuyPolish/PolaUITests/SnapshotFailedTests
      - name: "Upload PolaUITests-FailureDiffs"
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: PolaUITests-FailureDiffs
          path: BuyPolish/PolaUITests/FailureDiffs
      - name: "Upload PolaTests-FailureDiffs"
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: PolaTests-FailureDiffs
          path: BuyPolish/PolaTests/FailureDiffs


