name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: Lint, unit & ui tests
    runs-on: macos-12
    defaults:
      run:
        working-directory: BuyPolish
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache bundler gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Cache pods
        uses: actions/cache@v3
        with:
          path: BuyPolish/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Bundler
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Pod install
        run: bundle exec pod install
      - name: Run tests
        run: bundle exec fastlane tests
      - name: Codecov
        uses: codecov/codecov-action@v1
      - name: "Upload Tests results"
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: xcresult
          path: BuyPolish/fastlane/test_output
