// Generated using SwiftGen, by O.Halligon — https://github.com/AliSoftware/SwiftGen

import UIKit.UIImage

enum Asset: String {
  case Bg_delete_basket = "bg_delete_basket"
  case Bg_delete_wishlist = "bg_delete_wishlist"
  case Empty_bag = "empty_bag"
  case Error = "error"
  case For_her = "for_her"
  case For_him = "for_him"
  case Ic_bag = "ic_bag"
  case Ic_bag_selected = "ic_bag_selected"
  case Ic_browse = "ic_browse"
  case Ic_browse_selected = "ic_browse_selected"
  case Ic_checkbox_off = "ic_checkbox_off"
  case Ic_checkbox_on = "ic_checkbox_on"
  case Ic_chevron_down = "ic_chevron_down"
  case Ic_chevron_right = "ic_chevron_right"
  case Ic_close = "ic_close"
  case Ic_close_toast = "ic_close_toast"
  case Ic_cross_red = "ic_cross_red"
  case Ic_do_ulubionych = "ic_do_ulubionych"
  case Ic_dropdown = "ic_dropdown"
  case Ic_dropdown_small = "ic_dropdown_small"
  case Ic_facebook = "ic_facebook"
  case Ic_favorites = "ic_favorites"
  case Ic_favorites_selected = "ic_favorites_selected"
  case Ic_fb = "ic_fb"
  case Ic_filter = "ic_filter"
  case Ic_home = "ic_home"
  case Ic_home_selected = "ic_home_selected"
  case Ic_info = "ic_info"
  case Ic_instagram = "ic_instagram"
  case Ic_navigation_back = "ic_navigation_back"
  case Ic_settings = "ic_settings"
  case Ic_settings_selected = "ic_settings_selected"
  case Ic_share = "ic_share"
  case Ic_tick = "ic_tick"
  case Ic_w_ulubionych = "ic_w_ulubionych"
  case Im_sukces = "im_sukces"
  case Img_password = "img_password"
  case Img_wieszak = "img_wieszak"
  case Kasa_fail = "kasa_fail"
  case Logo = "logo"
  case Onb_img1_5 = "onb_img1_5"
  case Onb_img1_6 = "onb_img1_6"
  case Onb_img1_6p = "onb_img1_6p"
  case Onb_img2_4 = "onb_img2_4"
  case Onb_img2_5 = "onb_img2_5"
  case Onb_img2_6 = "onb_img2_6"
  case Onb_img2_6p = "onb_img2_6p"
  case Onb_img_3 = "onb_img_3"
  case Onb_img_3_4 = "onb_img_3_4"
  case Onb_img_3_6 = "onb_img_3_6"
  case Onb_img_3_6p = "onb_img_3_6p"
  case Onb_img_4 = "onb_img_4"
  case Onb_img_4_4 = "onb_img_4_4"
  case Onb_img_4_6 = "onb_img_4_6"
  case Onb_img_4_6p = "onb_img_4_6p"
  case Onb_iphone_5 = "onb_iphone_5"
  case Onb_iphone_6 = "onb_iphone_6"
  case Onb_iphone_6p = "onb_iphone_6p"
  case Onb_iphone_big = "onb_iphone_big"
  case Onb_iphone_big_4 = "onb_iphone_big_4"
  case Onb_iphone_big_4_vert = "onb_iphone_big_4_vert"
  case Onb_iphone_big_5_vert = "onb_iphone_big_5_vert"
  case Onb_iphone_big_6 = "onb_iphone_big_6"
  case Onb_iphone_big_6_vert = "onb_iphone_big_6_vert"
  case Onb_iphone_big_6p = "onb_iphone_big_6p"
  case Onb_iphone_big_6p_vert = "onb_iphone_big_6p_vert"
  case Onb_logo_5 = "onb_logo_5"
  case Onb_logo_6 = "onb_logo_6"
  case Onb_logo_6p = "onb_logo_6p"
  case Onb_push = "onb_push"
  case Onb_push_4 = "onb_push_4"
  case Onb_push_6 = "onb_push_6"
  case Onb_push_6p = "onb_push_6p"
  case Profile_header = "profile_header"
  case Profile_logo = "profile_logo"
  case Refresh = "refresh"
  case Slider = "slider"
  case SplashImage4s = "SplashImage4s"
  case SplashImage5s = "SplashImage5s"
  case SplashImage6 = "SplashImage6"
  case SplashImage6p = "SplashImage6p"

  var image: UIImage {
    return UIImage(asset: self)
  }
}

extension UIImage {
  convenience init!(asset: Asset) {
    self.init(named: asset.rawValue)
  }
}

